FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/ai_sidekick

COPY requirements_bot.txt ./
RUN pip install --no-cache-dir -r requirements_bot.txt

ENV PYTHONPATH=/tmp/ai_sidekick/bot
